############################# English ############################
[en]
languageName = "En"
title = "Radius"
contentDir = "content"
weight = 1
########### footer content ##########
footer_menu_left = "Learn"
footer_menu_middle = "Community"
footer_menu_right = "News"
# copyright
copyright = "© Radius Authors"
